//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatacollectionAPI.VendorsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int productId { get; set; }
        public string productName { get; set; }
        public string serialNumber { get; set; }
        public string imageLocation { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<int> productTypeId { get; set; }
        public bool isDisable { get; set; }
        public int createdBy { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<int> vendorId { get; set; }
        public string price { get; set; }
    
        public virtual productType productType { get; set; }
    }
}
